CREATE TABLE IF NOT EXISTS urls (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255),
	created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS checks (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	url_id BIGINT REFERENCES urls(id),
	response_code INTEGER,
	h1 VARCHAR(255),
	title VARCHAR(255),
	description VARCHAR(255),
	created_at TIMESTAMP
);